services:
  app:
    build: .
    volumes:
      - .:/app         # 현재 디렉토리를 컨테이너의 /app에 마운트
    ports:
      - "3000:3000"  # 포트 바인딩 확인
    stdin_open: true   # -i 옵션 (표준 입력 열기)
    tty: true          # -t 옵션 (터미널 세션 유지)
    command: sh        # 컨테이너 실행 시 기본으로 쉘 실행
